# Generated by Django 6.0 on 2025-12-10 10:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Culto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(auto_now_add=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hermano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=20, unique=True)),
                ('fecha_nacimiento', models.DateField()),
                ('fecha_ingreso', models.DateField()),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo'), ('Suspendido', 'Suspendido')], default='Activo', max_length=10)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='hermanos/')),
            ],
        ),
        migrations.CreateModel(
            name='TipoCulto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importe', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('fecha', models.DateField(auto_now_add=True)),
                ('estado_pago', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Pagado', 'Pagado')], default='Pendiente', max_length=10)),
                ('periodo', models.CharField(choices=[('sem1', '1er Semestre'), ('sem2', '2do Semestre')], default='sem1', max_length=10)),
                ('hermano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas', to='lumenApp.hermano')),
            ],
        ),
        migrations.CreateModel(
            name='HermanoRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(auto_now_add=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('hermano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lumenApp.hermano')),
            ],
        ),
        migrations.CreateModel(
            name='ParticipacionCulto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tramo', models.IntegerField(blank=True, null=True)),
                ('culto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lumenApp.culto')),
                ('hermano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lumenApp.hermano')),
            ],
        ),
        migrations.AddField(
            model_name='culto',
            name='hermanos',
            field=models.ManyToManyField(related_name='cultos', through='lumenApp.ParticipacionCulto', to='lumenApp.hermano'),
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('hermanos', models.ManyToManyField(related_name='roles', through='lumenApp.HermanoRol', to='lumenApp.hermano')),
            ],
        ),
        migrations.AddField(
            model_name='participacionculto',
            name='rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lumenApp.rol'),
        ),
        migrations.AddField(
            model_name='hermanorol',
            name='rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lumenApp.rol'),
        ),
        migrations.AddField(
            model_name='culto',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lumenApp.tipoculto'),
        ),
        migrations.AlterUniqueTogether(
            name='participacionculto',
            unique_together={('hermano', 'culto', 'rol')},
        ),
        migrations.AlterUniqueTogether(
            name='hermanorol',
            unique_together={('hermano', 'rol')},
        ),
    ]
